### ISSUE TITLE
Fix processing bug where concatenation of monthly weather into yearly fails in some cases

### ISSUE THREAD

**Issue by mcmancini** [mcmancini/Era5Weather#21]
When attempting to run the `python download_and_process_era5.py --start 2010 --end 2023 --options process` after having downloaded the relevant data, the first step of the processing script is to take the downloaded files (which contain weather observations by month) and combine them into a single file for each year of interest. This works for the most part but fails for some reason for year 2015 with the following error:  
```
(era-weather) PS D:\Documents\GitHub\Era5Weather> python .\download_and_process_era5.py --start 2010 --end 2023 --options process
Traceback (most recent call last):
  File "D:\Documents\GitHub\Era5Weather\download_and_process_era5.py", line 72, in <module>
    yearly_file_list = aggregate_years(
                       ^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\Era5Weather\era_weather\rechunk_weather.py", line 78, in aggregate_years
    combined_dataset = xr.concat(datasets, dim="valid_time")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcm216\.conda\envs\era-weather\Lib\site-packages\xarray\core\concat.py", line 276, in concat
    return _dataset_concat(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mcm216\.conda\envs\era-weather\Lib\site-packages\xarray\core\concat.py", line 626, in _dataset_concat
    raise ValueError(
ValueError: coordinate 'expver' not present in all datasets.
```

Figure out what the error is about and fix it.

**Comment by mcmancini** [comment]
It looks like the issue wsa not from the code I wrote, but from some corrupted monthly files. I do not konw what caused the download process to end up with some corrupt files for the year 2015. Deleting and redownloading those files fixed the issue.
